version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  flowise:
    build: .
    container_name: flowise
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    volumes:
      - flowise_data:/root/.flowise
    restart: unless-stopped

volumes:
  ollama_data:
  flowise_data:
